# Generated by Django 6.0 on 2026-01-09 07:52

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_login',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(default='employee', max_length=128)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='verification_table',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('generated_code', models.IntegerField(default=users.models.generate_unique_code, unique=True)),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
